In [2]:
import numpy as np

In [4]:
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [6]:
arr1

array([[2, 1, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [8]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [10]:
arr1.flatten() #Return a copy of the array collapsed into one dimension

array([2, 1, 2, 2, 2, 1, 1, 1, 2])

In [12]:
#expand dimension
arr = np.array([1, 2, 3, 4])

In [14]:
arr

array([1, 2, 3, 4])

In [16]:
arr.ndim

1

In [20]:
np.expand_dims(arr, axis=0) #increase the dimension by 1 in the provided axis, 0 means rows(x axis), 1 means column wise

array([[1, 2, 3, 4]])

In [22]:
np.expand_dims(arr, axis=1) #column wise

array([[1],
       [2],
       [3],
       [4]])

In [24]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.expand_dims(arr, axis = 0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [32]:
np.expand_dims(arr, axis = 0).ndim #row wise

3

In [34]:
np.expand_dims(arr, axis = 1) #column wise

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [36]:
np.expand_dims(arr, axis = 0).ndim

3

In [38]:
a = np.array([[1], [2], [3]])

In [40]:
a

array([[1],
       [2],
       [3]])

In [42]:
a.ndim

2

In [44]:
#squeezing the dimesion 
np.squeeze(a) #Remove axes of length one from 'a'

array([1, 2, 3])

In [46]:
a

array([[1],
       [2],
       [3]])

In [48]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [50]:
arr1

array([[2, 1, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [52]:
np.repeat(arr1, 2)

array([2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2])

In [54]:
np.repeat(arr1, 2, axis=0)

array([[2, 1, 2],
       [2, 1, 2],
       [2, 2, 1],
       [2, 2, 1],
       [1, 1, 2],
       [1, 1, 2]])

In [58]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [62]:
np.repeat(arr2, 3, axis=0)

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [64]:
np.repeat(arr2, 3, axis=1)

array([[2, 2, 2, 2, 2, 2, 1, 1, 1],
       [2, 2, 2, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 1, 1, 1, 2, 2, 2]])

In [66]:
a

array([[1],
       [2],
       [3]])

In [70]:
np.roll(a, -1) #shift place

array([[2],
       [3],
       [1]])

In [72]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [74]:
c = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

In [76]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [78]:
np.roll(c, -1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [80]:
np.roll(c, 2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [82]:
np.roll(c, 2, axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [84]:
arr1

array([[2, 1, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [86]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [88]:
arr1+arr2

array([[4, 3, 3],
       [4, 3, 2],
       [3, 2, 4]])

In [90]:
arr1-arr2

array([[ 0, -1,  1],
       [ 0,  1,  0],
       [-1,  0,  0]])

In [92]:
arr1*arr2

array([[4, 2, 2],
       [4, 2, 1],
       [2, 1, 4]])

In [94]:
arr1 > arr2

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])

In [96]:
arr1

array([[2, 1, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [100]:
~arr1  #negation

array([[-3, -2, -3],
       [-3, -3, -2],
       [-2, -2, -3]])

In [102]:
#operations on numpy string array

d = np.array(["pw", "skills"])

In [104]:
d

array(['pw', 'skills'], dtype='<U6')

In [106]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [108]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [110]:
#mathematical function

In [112]:
arr1

array([[2, 1, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [114]:
np.sin(arr1)

array([[0.90929743, 0.84147098, 0.90929743],
       [0.90929743, 0.90929743, 0.84147098],
       [0.84147098, 0.84147098, 0.90929743]])

In [116]:
np.cos(arr1)

array([[-0.41614684,  0.54030231, -0.41614684],
       [-0.41614684, -0.41614684,  0.54030231],
       [ 0.54030231,  0.54030231, -0.41614684]])

In [118]:
np.tan(arr1)

array([[-2.18503986,  1.55740772, -2.18503986],
       [-2.18503986, -2.18503986,  1.55740772],
       [ 1.55740772,  1.55740772, -2.18503986]])

In [120]:
np.log(arr1)

array([[0.69314718, 0.        , 0.69314718],
       [0.69314718, 0.69314718, 0.        ],
       [0.        , 0.        , 0.69314718]])

In [122]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 7.3890561 ]])

In [124]:
np.power(arr1, 3)

array([[8, 1, 8],
       [8, 8, 1],
       [1, 1, 8]], dtype=int32)

In [126]:
np.max(arr1)

2

In [130]:
np.min(arr1)

1

In [132]:
np.mean(arr1)

1.5555555555555556

In [134]:
np.std(arr1)

0.4969039949999533

In [136]:
np.var(arr1)

0.2469135802469136

In [138]:
arr1-arr2

array([[ 0, -1,  1],
       [ 0,  1,  0],
       [-1,  0,  0]])

In [142]:
np.subtract(arr1, arr2)  #another method

array([[ 0, -1,  1],
       [ 0,  1,  0],
       [-1,  0,  0]])

In [144]:
arr1*arr2

array([[4, 2, 2],
       [4, 2, 1],
       [2, 1, 4]])

In [148]:
np.multiply(arr1, arr2)  #another method

array([[4, 2, 2],
       [4, 2, 1],
       [2, 1, 4]])

In [150]:
np.mod(arr1, arr2)  #return element wise remainder

array([[0, 1, 0],
       [0, 0, 0],
       [1, 0, 0]])

In [152]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.        ],
       [1.        , 1.        , 1.41421356]])

In [154]:
#sorting and searching in numpy array
e = np.array([5, 6, 1, 2])

In [156]:
e

array([5, 6, 1, 2])

In [158]:
np.sort(e)

array([1, 2, 5, 6])

In [162]:
f = np.array([5, 199, 200, 6, 7, 8])
f

array([  5, 199, 200,   6,   7,   8])

In [164]:
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [166]:
np.searchsorted(f, 170) #find indices where elements should be inserted to maintain order

6

In [168]:
f = np.array([5, 199, 200, 0, 0, 0, 0, 6, 7, 8])
f

array([  5, 199, 200,   0,   0,   0,   0,   6,   7,   8])

In [170]:
np.count_nonzero(f)

6

In [172]:
f>0

array([ True,  True,  True, False, False, False, False,  True,  True,
        True])

In [174]:
f[f>0]

array([  5, 199, 200,   6,   7,   8])

In [178]:
np.where(f>0) #same as above condition

(array([0, 1, 2, 7, 8, 9], dtype=int64),)

In [182]:
np.extract(f>0, f) #same as above condition

array([  5, 199, 200,   6,   7,   8])

In [184]:
f

array([  5, 199, 200,   0,   0,   0,   0,   6,   7,   8])

In [186]:
f.byteswap() #swap the bytes of the array elements

array([  83886080, -956301312, -939524096,          0,          0,
                0,          0,  100663296,  117440512,  134217728])

In [188]:
#numpy library for matrix

In [190]:
import numpy.matlib as nm
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [192]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [194]:
#numpy linear algebra(optional)

In [196]:
arr1

array([[2, 1, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [198]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [200]:
arr1@arr2

array([[10,  7,  7],
       [10,  7,  6],
       [ 8,  5,  6]])

In [202]:
arr1

array([[2, 1, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [208]:
np.linalg.det(arr1)

2.9999999999999996

In [210]:
np.linalg.det(arr2)

-2.0

In [214]:
#in matrix you can not divide by another matrix, you have inverse
np.linalg.inv(arr1)

array([[ 1.00000000e+00, -5.55111512e-17, -1.00000000e+00],
       [-1.00000000e+00,  6.66666667e-01,  6.66666667e-01],
       [ 0.00000000e+00, -3.33333333e-01,  6.66666667e-01]])

In [216]:
np.linalg.inv(arr2)

array([[-0.5,  1.5, -0.5],
       [ 1. , -1. , -0. ],
       [ 0. , -1. ,  1. ]])

In [218]:
a = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [220]:
b = np.array([16, 8, 0])

In [222]:
np.linalg.solve(a, b)

array([2.59630607, 0.84432718, 2.21635884])