In [1]:
import numpy as np

In [3]:
np.zeros(5) #return a new array of given shape and type, filled with zeros.

array([0., 0., 0., 0., 0.])

In [5]:
a = np.zeros(5)

In [7]:
a

array([0., 0., 0., 0., 0.])

In [9]:
a.ndim

1

In [11]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
b = np.zeros((3, 4))

In [17]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
b.ndim  ##two dimension

2

In [21]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.twos(5) #doesn't exist

AttributeError: module 'numpy' has no attribute 'twos'

In [29]:
np.array([[2, 2, 2], [2, 2, 2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [31]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
arr = np.zeros((3, 4))

In [35]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
arr.ndim

2

In [39]:
#one dimension array

In [41]:
np.zeros(3)

array([0., 0., 0.])

In [43]:
#two dimension array

In [45]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
#three dimension array

In [49]:
np.zeros((1, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [51]:
a = np.zeros((1, 3, 4))

In [53]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
arr.ndim

2

In [57]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [59]:
np.zeros((1, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [61]:
#four dimension array

In [63]:
np.zeros((1, 1, 3, 3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [65]:
b = np.zeros((1, 1, 3, 3))

In [67]:
b.ndim

4

In [69]:
#five dimension array

In [71]:
np.zeros((1, 1, 1, 3, 3))

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]]])

In [73]:
c = np.zeros((1, 1, 1, 3, 3))

In [75]:
c

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]]])

In [77]:
c.ndim

5

In [79]:
arr = np.zeros((3, 4))

In [81]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [85]:
a = arr+5

In [87]:
a*2

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [89]:
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [91]:
a - 1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [93]:
np.eye(3) #return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [95]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [97]:
np.empty((3, 4)) #it gives you random numbers or values

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [99]:
np.empty((3, 4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [101]:
#optional>> random module

In [103]:
import random

In [105]:
random.choice((1, 2, 3, 4, 5))

2

In [107]:
random.choice("Chandan")

'a'

In [109]:
random.randrange(1, 10)

9

In [111]:
random.random() #a random no generated between 0(included) and 1(excluded)

0.9218567065269818

In [113]:
lis = [1, 2, 3, 4, 5]
lis

[1, 2, 3, 4, 5]

In [115]:
random.shuffle(lis)

In [117]:
lis

[4, 1, 2, 5, 3]

In [119]:
random.uniform(7, 14)

9.151997723517999

In [121]:
#random numbers related concept in numpy

np.array([])

array([], dtype=float64)

In [123]:
np.random.random_sample()

0.6703109868707068

In [125]:
np.random.random_sample((5, )) #one dimension array of 5 random numbers

array([0.76384645, 0.11588785, 0.42396109, 0.03576873, 0.52593262])

In [127]:
np.random.rand(1)

array([0.83838409])

In [129]:
np.random.rand(2, 3) #return a sample (or samples) from the "standard normal" dustribution. (returns data from a curve)

array([[0.68054465, 0.29376759, 0.23295131],
       [0.98308684, 0.83856483, 0.95960842]])

In [131]:
np.random.randn() #return a sample (or samples) from the "standard normal" dustribution. (returns data from a curve)

0.09028114946095657

In [133]:
np.random.randint(1, 5, size = (3, 4))

array([[1, 4, 2, 2],
       [2, 3, 4, 1],
       [2, 1, 4, 3]])

In [135]:
arr = np.random.randint(1, 5, size = (3, 4))

In [137]:
arr.ndim

2

In [139]:
arr.shape

(3, 4)

In [141]:
arr.size

12

In [143]:
arr

array([[4, 4, 1, 4],
       [1, 2, 1, 4],
       [4, 4, 4, 2]])

In [145]:
#reshaping of array
arr.reshape(2, 6) #returns an array containing the same data with a new shape

array([[4, 4, 1, 4, 1, 2],
       [1, 4, 4, 4, 4, 2]])

In [147]:
arr1 = arr.reshape(2, 6)

In [149]:
arr1

array([[4, 4, 1, 4, 1, 2],
       [1, 4, 4, 4, 4, 2]])

In [151]:
arr1.size

12

In [153]:
arr1.shape

(2, 6)

In [155]:
arr1.ndim

2

In [157]:
#array size will never change, always reshape parameter should be multiplication of original array size

In [159]:
arr

array([[4, 4, 1, 4],
       [1, 2, 1, 4],
       [4, 4, 4, 2]])

In [161]:
arr.reshape(3, 2)

ValueError: cannot reshape array of size 12 into shape (3,2)

In [163]:
arr.reshape(3, 3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [165]:
arr.reshape(3, 4)

array([[4, 4, 1, 4],
       [1, 2, 1, 4],
       [4, 4, 4, 2]])

In [169]:
arr.reshape(4, 3)

array([[4, 4, 1],
       [4, 1, 2],
       [1, 4, 4],
       [4, 4, 2]])

In [171]:
arr.reshape(1, 12)

array([[4, 4, 1, 4, 1, 2, 1, 4, 4, 4, 4, 2]])

In [175]:
arr.reshape(12, 1)

array([[4],
       [4],
       [1],
       [4],
       [1],
       [2],
       [1],
       [4],
       [4],
       [4],
       [4],
       [2]])

In [177]:
#case when you dont know in reshape what should be the row or column count 
#use any negative value for rows and columns
arr.reshape(4, -1)

array([[4, 4, 1],
       [4, 1, 2],
       [1, 4, 4],
       [4, 4, 2]])

In [179]:
arr.reshape(4, -100) #put any negative value it will do the same

array([[4, 4, 1],
       [4, 1, 2],
       [1, 4, 4],
       [4, 4, 2]])

In [181]:
arr.reshape(-1,4)   #when i don't know the no of rows to be put but i know the no of columns 

array([[4, 4, 1, 4],
       [1, 2, 1, 4],
       [4, 4, 4, 2]])

In [183]:
arr

array([[4, 4, 1, 4],
       [1, 2, 1, 4],
       [4, 4, 4, 2]])

In [187]:
arr.reshape(12, 1)  #want to reshape this array

array([[4],
       [4],
       [1],
       [4],
       [1],
       [2],
       [1],
       [4],
       [4],
       [4],
       [4],
       [2]])

In [191]:
arr.reshape(12, 1).base  #when you want to reshape the original array

array([[4, 4, 1, 4],
       [1, 2, 1, 4],
       [4, 4, 4, 2]])

In [193]:
arr.reshape(2, 2, 3) #multiplication should be equals to arr size

array([[[4, 4, 1],
        [4, 1, 2]],

       [[1, 4, 4],
        [4, 4, 2]]])

In [195]:
arr.reshape(1, 2, 2, 3)

array([[[[4, 4, 1],
         [4, 1, 2]],

        [[1, 4, 4],
         [4, 4, 2]]]])

In [197]:
arr.reshape(1, 2, 2, 3) #to know the dimension

array([[[[4, 4, 1],
         [4, 1, 2]],

        [[1, 4, 4],
         [4, 4, 2]]]])

In [201]:
arr.reshape(4, 3, 1) #3 rows 1 column repeated 4 times in the third dimension

array([[[4],
        [4],
        [1]],

       [[4],
        [1],
        [2]],

       [[1],
        [4],
        [4]],

       [[4],
        [4],
        [2]]])

In [203]:
#conditions on array
arr1=np.random.randint(1, 10, (5, 6))

In [205]:
arr1

array([[8, 1, 3, 8, 6, 9],
       [7, 4, 7, 2, 1, 8],
       [5, 8, 1, 3, 8, 5],
       [9, 8, 3, 1, 4, 4],
       [3, 9, 5, 1, 1, 7]])

In [207]:
arr1.shape

(5, 6)

In [209]:
arr1.size

30

In [211]:
arr1.ndim

2

In [213]:
arr1

array([[8, 1, 3, 8, 6, 9],
       [7, 4, 7, 2, 1, 8],
       [5, 8, 1, 3, 8, 5],
       [9, 8, 3, 1, 4, 4],
       [3, 9, 5, 1, 1, 7]])

In [215]:
arr1 > 3

array([[ True, False, False,  True,  True,  True],
       [ True,  True,  True, False, False,  True],
       [ True,  True, False, False,  True,  True],
       [ True,  True, False, False,  True,  True],
       [False,  True,  True, False, False,  True]])

In [221]:
arr1[arr1 > 3] #select all the elements of arr1 where the condition is true and greater than 3

array([8, 8, 6, 9, 7, 4, 7, 8, 5, 8, 8, 5, 9, 8, 4, 4, 9, 5, 7])

In [223]:
arr1[arr1 < 3]

array([1, 2, 1, 1, 1, 1, 1])

In [225]:
arr1

array([[8, 1, 3, 8, 6, 9],
       [7, 4, 7, 2, 1, 8],
       [5, 8, 1, 3, 8, 5],
       [9, 8, 3, 1, 4, 4],
       [3, 9, 5, 1, 1, 7]])

In [227]:
#to access elements in an array

In [229]:
arr1[0]

array([8, 1, 3, 8, 6, 9])

In [231]:
arr1[1]

array([7, 4, 7, 2, 1, 8])

In [235]:
arr1[1][0]

7

In [245]:
#slicing

In [247]:
#from 0th row to 2nd row
arr1[0:3]

array([[8, 1, 3, 8, 6, 9],
       [7, 4, 7, 2, 1, 8],
       [5, 8, 1, 3, 8, 5]])

In [249]:
#0 to 2nd row and 0th and 2nd column
arr1[0:3,[0,2]]

array([[8, 3],
       [7, 7],
       [5, 1]])

In [251]:
#slicing on both rows and columns together
arr1

array([[8, 1, 3, 8, 6, 9],
       [7, 4, 7, 2, 1, 8],
       [5, 8, 1, 3, 8, 5],
       [9, 8, 3, 1, 4, 4],
       [3, 9, 5, 1, 1, 7]])

In [253]:
arr1[0:3, 1:3]

array([[1, 3],
       [4, 7],
       [8, 1]])

In [255]:
arr1[0:3, [0, 1]]

array([[8, 1],
       [7, 4],
       [5, 8]])

In [257]:
arr1[0, [1, 3]]

array([1, 8])

In [259]:
arr1[2:4, [0, 3]]

array([[5, 3],
       [9, 1]])

In [261]:
arr1[2:5]

array([[5, 8, 1, 3, 8, 5],
       [9, 8, 3, 1, 4, 4],
       [3, 9, 5, 1, 1, 7]])

In [263]:
arr1[2:5, 0:2]

array([[5, 8],
       [9, 8],
       [3, 9]])

In [265]:
#mathematical operations on two arrays 
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [267]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 1]])

In [269]:
arr2

array([[2, 2, 2],
       [2, 1, 1],
       [2, 1, 1]])

In [271]:
arr1+arr2

array([[3, 4, 4],
       [3, 3, 3],
       [3, 3, 2]])

In [273]:
arr1-arr2

array([[-1,  0,  0],
       [-1,  1,  1],
       [-1,  1,  0]])

In [275]:
arr1 * arr2 #index wise multiplication

array([[2, 4, 4],
       [2, 2, 2],
       [2, 2, 1]])

In [277]:
arr1/arr2 #index wise division

array([[0.5, 1. , 1. ],
       [0.5, 2. , 2. ],
       [0.5, 2. , 1. ]])

In [279]:
4/0  #in python it used to give you ZeroDivisonError

ZeroDivisionError: division by zero

In [281]:
arr1/0

C:\Users\Chandan Singh\AppData\Local\Temp\ipykernel_35672\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [283]:
#matrix multiplication >> matrix is a specialised 2-D array
#matrix multiplication is different from index wise multiplication

In [287]:
arr1 @ arr2  #using @

array([[10,  6,  6],
       [10,  6,  6],
       [ 8,  5,  5]])

In [289]:
np.dot(arr1, arr2)  #anothe way for matrix multiplication

array([[10,  6,  6],
       [10,  6,  6],
       [ 8,  5,  5]])

In [291]:
#broadcasting 

In [293]:
arr =np.zeros((3, 4))

In [295]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [297]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [299]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [301]:
a = np.array([1, 2, 3, 4])

In [303]:
a

array([1, 2, 3, 4])

In [305]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [307]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [311]:
#Transpose >> converting rows to columns and columns to rows
##it works for two dimension

In [313]:
a = np.array([[1, 2, 3, 4]])

In [315]:
a

array([[1, 2, 3, 4]])

In [317]:
a.T

array([[1],
       [2],
       [3],
       [4]])

In [319]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 1]])

In [321]:
arr1.T

array([[1, 1, 1],
       [2, 2, 2],
       [2, 2, 1]])